export const styles = {
  operatorCard: { border: "1px solid #fed7aa", background: "linear-gradient(180deg, #fff7ed 0%, #ffffff 56%)" },
  operatorHeader: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "start" },
  operatorStep: { background: "#0f172a", color: "white", borderRadius: 999, padding: "7px 10px", fontWeight: 1000, fontSize: 12 },
  operatorText: { margin: "8px 0 0", color: "#475569", fontWeight: 800, lineHeight: 1.45 },
  operatorProgress: { display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 6, marginTop: 14 },
  progressDot: { height: 30, borderRadius: 999, display: "grid", placeItems: "center", background: "#f1f5f9", border: "1px solid #e2e8f0", color: "#64748b", fontWeight: 1000, fontSize: 12 },
  progressDotActive: { height: 30, borderRadius: 999, display: "grid", placeItems: "center", background: "#f97316", border: "1px solid #fb923c", color: "white", fontWeight: 1000, fontSize: 12 },
  checkList: { display: "grid", gap: 8, marginTop: 14 },
  checkLine: { display: "flex", gap: 8, alignItems: "center", color: "#334155", fontWeight: 850, fontSize: 13 },
  checkOk: { width: 22, height: 22, borderRadius: 999, display: "grid", placeItems: "center", background: "#dcfce7", color: "#166534", fontWeight: 1000 },
  checkPending: { width: 22, height: 22, borderRadius: 999, display: "grid", placeItems: "center", background: "#fef3c7", color: "#92400e", fontWeight: 1000 },
  operatorWarning: { background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", borderRadius: 14, padding: 12, fontWeight: 850, marginTop: 14 },
  operatorInfo: { background: "#eff6ff", border: "1px solid #bfdbfe", color: "#1d4ed8", borderRadius: 14, padding: 12, fontWeight: 850, marginTop: 14 },
  operatorPrimary: { width: "100%", border: "none", background: "#f97316", color: "white", borderRadius: 13, padding: "13px 16px", fontWeight: 1000, marginTop: 12, boxShadow: "0 10px 20px rgba(249,115,22,.22)" },
  operatorSecondary: { width: "100%", border: "1px solid #fed7aa", background: "white", color: "#c2410c", borderRadius: 13, padding: "12px 16px", fontWeight: 1000, marginTop: 8 },
  page: { minHeight: "100vh", padding: 20, background: "#f1f5f9", color: "#0f172a" },
  hero: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, padding: 22, borderRadius: 24, background: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)", color: "white", boxShadow: "0 18px 40px rgba(15,23,42,.18)", marginBottom: 16 },
  kicker: { margin: 0, color: "#fb923c", fontSize: 12, fontWeight: 1000, textTransform: "uppercase", letterSpacing: ".08em" },
  title: { margin: "3px 0 0", fontSize: 34, fontWeight: 1000, letterSpacing: "-.03em" },
  subtitle: { margin: "8px 0 0", color: "#cbd5e1", fontWeight: 700 },
  heroActions: { display: "flex", gap: 10, flexWrap: "wrap" },
  secondaryHeroButton: { textDecoration: "none", border: "1px solid rgba(255,255,255,.22)", background: "rgba(255,255,255,.08)", color: "white", borderRadius: 14, padding: "12px 16px", fontWeight: 1000, cursor: "pointer" },
  success: { background: "#ecfdf5", color: "#047857", border: "1px solid #86efac", borderRadius: 14, padding: 12, marginBottom: 14, fontWeight: 800 },
  error: { background: "#fff1f0", color: "#b42318", border: "1px solid #fecdca", borderRadius: 14, padding: 12, marginBottom: 14, fontWeight: 800 },
  metricsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 12, marginBottom: 16 },
  metric: { background: "white", border: "1px solid #e2e8f0", borderRadius: 18, padding: 14, display: "grid", gap: 5, boxShadow: "0 10px 22px rgba(15,23,42,.06)" },
  metricTones: { dark: { color: "#0f172a" }, ok: { color: "#047857", background: "#ecfdf5", borderColor: "#bbf7d0" }, info: { color: "#1d4ed8", background: "#eff6ff", borderColor: "#bfdbfe" }, warning: { color: "#b45309", background: "#fffbeb", borderColor: "#fde68a" }, muted: { color: "#475569", background: "#f8fafc" }, orange: { color: "#c2410c", background: "#fff7ed", borderColor: "#fed7aa" } },
  layout: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 360px", gap: 16, alignItems: "start" },
  mainColumn: { display: "grid", gap: 16 },
  card: { background: "white", border: "1px solid #e2e8f0", borderRadius: 22, padding: 18, boxShadow: "0 14px 30px rgba(15,23,42,.06)" },
  cardNoPadding: { background: "white", border: "1px solid #e2e8f0", borderRadius: 22, overflow: "hidden", boxShadow: "0 14px 30px rgba(15,23,42,.06)" },
  sectionHeader: { marginBottom: 14 },
  eyebrow: { margin: 0, color: "#f97316", fontSize: 12, fontWeight: 1000, textTransform: "uppercase", letterSpacing: ".08em" },
  cardTitle: { margin: "3px 0 0", fontSize: 22, letterSpacing: "-.02em" },
  muted: { color: "#64748b", margin: "4px 0 0", fontWeight: 700 },
  itemGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(210px, 1fr))", gap: 12, alignItems: "end" },
  itemComposer: { display: "grid", gap: 12 },
  tipoSelector: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  tipoButton: { border: "1px solid #cbd5e1", background: "white", color: "#334155", borderRadius: 14, padding: "12px 14px", fontWeight: 1000, cursor: "pointer" },
  tipoButtonActive: { border: "1px solid #f97316", background: "#fff7ed", color: "#c2410c", borderRadius: 14, padding: "12px 14px", fontWeight: 1000, cursor: "pointer", boxShadow: "0 10px 22px rgba(249,115,22,.12)" },
  selectorHint: { background: "#fff7ed", border: "1px solid #fed7aa", color: "#9a3412", borderRadius: 13, padding: "10px 12px", fontWeight: 800, fontSize: 13 },
  itemsPicker: { display: "grid", gap: 10, maxHeight: 360, overflowY: "auto", paddingRight: 4 },
  tallerOption: { width: "100%", border: "1px solid #e2e8f0", background: "white", borderRadius: 16, padding: 10, display: "grid", gridTemplateColumns: "64px minmax(0, 1fr) auto", gap: 12, alignItems: "center", textAlign: "left", cursor: "pointer" },
  tallerOptionSelected: { width: "100%", border: "1px solid #f97316", background: "#fff7ed", borderRadius: 16, padding: 10, display: "grid", gridTemplateColumns: "64px minmax(0, 1fr) auto", gap: 12, alignItems: "center", textAlign: "left", cursor: "pointer", boxShadow: "0 10px 22px rgba(249,115,22,.15)" },
  optionImageBox: { width: 58, height: 58, borderRadius: 14, background: "#f8fafc", border: "1px solid #e2e8f0", display: "grid", placeItems: "center", overflow: "hidden" },
  serviceIcon: { fontSize: 28 },
  optionBody: { minWidth: 0, display: "grid", gap: 4 },
  optionTop: { display: "flex", gap: 8, justifyContent: "space-between", alignItems: "center" },
  optionMeta: { display: "flex", gap: 8, flexWrap: "wrap", color: "#64748b", fontSize: 12, fontWeight: 800 },
  serviceBadge: { background: "#ecfdf5", color: "#047857", borderRadius: 999, padding: "5px 8px", fontSize: 12, fontWeight: 1000 },
  partBadge: { background: "#eff6ff", color: "#1d4ed8", borderRadius: 999, padding: "5px 8px", fontSize: 12, fontWeight: 1000 },
  optionPrice: { whiteSpace: "nowrap", fontSize: 15 },
  selectedItemBox: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", background: "#ecfdf5", border: "1px solid #bbf7d0", borderRadius: 16, padding: 12 },
  itemFormRow: { display: "grid", gridTemplateColumns: "160px 180px minmax(180px, 1fr)", gap: 12, alignItems: "end" },
  field: { display: "grid", gap: 7, fontSize: 14, fontWeight: 900 },
  label: { color: "#334155" },
  input: { width: "100%", border: "1px solid #cbd5e1", borderRadius: 13, padding: "12px 13px", fontWeight: 700, color: "#0f172a", boxSizing: "border-box", background: "white" },
  primaryButton: { border: "none", background: "#f97316", color: "white", borderRadius: 13, padding: "12px 16px", fontWeight: 1000, cursor: "pointer", boxShadow: "0 10px 20px rgba(249,115,22,.22)" },
  secondaryButtonFull: { width: "100%", border: "1px solid #cbd5e1", background: "white", color: "#0f172a", borderRadius: 13, padding: "12px 16px", fontWeight: 1000, cursor: "pointer", textAlign: "center" },
  tableHeader: { padding: 18, borderBottom: "1px solid #e2e8f0" },
  itemsList: { display: "grid", gap: 10, padding: 16 },
  itemCard: { border: "1px solid #e2e8f0", borderRadius: 18, padding: 14, display: "grid", gap: 12, background: "white" },
  itemCardMuted: { border: "1px solid #e2e8f0", borderRadius: 18, padding: 14, display: "grid", gap: 12, background: "#f8fafc", opacity: 0.78 },
  itemTop: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "start" },
  itemTitleLine: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  itemTitle: { fontSize: 16 },
  itemBottom: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", borderTop: "1px solid #f1f5f9", paddingTop: 10 },
  itemActions: { display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" },
  smallPrimary: { border: "none", background: "#0f172a", color: "white", borderRadius: 11, padding: "8px 10px", fontWeight: 900, cursor: "pointer" },
  smallSecondary: { border: "1px solid #cbd5e1", background: "white", color: "#0f172a", borderRadius: 11, padding: "8px 10px", fontWeight: 900, cursor: "pointer" },
  smallDanger: { border: "1px solid #fecaca", background: "#fff1f0", color: "#b42318", borderRadius: 11, padding: "8px 10px", fontWeight: 900, cursor: "pointer" },
  smallMuted: { color: "#64748b", fontWeight: 800 },
  sidePanel: { display: "grid", gap: 16, position: "sticky", top: 16 },
  sideTitle: { margin: "0 0 12px", fontSize: 20 },
  statusForm: { display: "grid", gap: 12 },
  billingBox: {
    display: "grid",
    gap: 10,
  },
  linkButton: {
    display: "block",
    textAlign: "center",
    textDecoration: "none",
    border: "none",
    background: "#f97316",
    color: "white",
    borderRadius: 12,
    padding: "11px 12px",
    fontWeight: 1000,
    cursor: "pointer",
  },
  note: { marginTop: 12, background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", borderRadius: 14, padding: 12, fontWeight: 800 },
  warningText: { margin: 0, background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", borderRadius: 14, padding: 12, fontWeight: 800 },
  infoBox: { background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 14, padding: 12, display: "grid", gap: 5, color: "#64748b" },
  timeline: { display: "grid", gap: 10, maxHeight: 480, overflowY: "auto" },
  eventItem: { borderLeft: "4px solid #f97316", background: "#f8fafc", borderRadius: 14, padding: 12, display: "grid", gap: 4, color: "#334155" },
  empty: { padding: 22, color: "#64748b", fontWeight: 900 },
  emptySmall: { color: "#64748b", fontWeight: 900, background: "#f8fafc", borderRadius: 14, padding: 12 },
  stageBadge: { borderRadius: 999, padding: "7px 10px", fontWeight: 1000, fontSize: 12, whiteSpace: "nowrap", border: "1px solid transparent" },
  stageTones: { ok: { background: "#dcfce7", color: "#166534", borderColor: "#bbf7d0" }, info: { background: "#eff6ff", color: "#1d4ed8", borderColor: "#bfdbfe" }, warning: { background: "#fef3c7", color: "#92400e", borderColor: "#fde68a" }, danger: { background: "#fee2e2", color: "#991b1b", borderColor: "#fecaca" } },
  state: { padding: 24, fontWeight: 900 },

  operatorCardCompact: {
    boxShadow: "0 10px 26px rgba(249,115,22,.10)",
  },
  operatorHeaderActions: {
    display: "flex",
    gap: 8,
    alignItems: "center",
  },
  operatorToggle: {
    border: "1px solid #fed7aa",
    background: "white",
    color: "#c2410c",
    borderRadius: 999,
    padding: "7px 10px",
    fontWeight: 1000,
    cursor: "pointer",
  },
  pageMobile: {
    padding: 10,
    overflowX: "hidden",
  },
  heroMobile: {
    display: "grid",
    gridTemplateColumns: "1fr",
    alignItems: "stretch",
    padding: 16,
    borderRadius: 20,
    gap: 14,
  },
  heroActionsMobile: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    width: "100%",
  },
  metricsGridMobile: {
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
  },
  layoutMobile: {
    gridTemplateColumns: "1fr",
    gap: 12,
  },
  mainColumnMobile: {
    gap: 12,
  },
  sidePanelMobile: {
    position: "static",
    display: "grid",
    gap: 12,
    width: "100%",
    minWidth: 0,
  },
  tipoSelectorMobile: {
    gridTemplateColumns: "1fr",
  },
  itemFormRowMobile: {
    gridTemplateColumns: "1fr",
    gap: 10,
  },
};
