import { colors, controls, radius, shadows, spacing, typography } from "../../../theme";

export const styles = {
  operatorCard: { border: `1px solid ${colors.primaryBorder}`, background: colors.primarySoft },
  operatorHeader: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "start" },
  operatorStep: { background: colors.topbar, color: colors.surface, borderRadius: radius.pill, padding: "7px 10px", fontWeight: typography.label.fontWeight, fontSize: typography.small.fontSize },
  operatorText: { margin: "8px 0 0", color: colors.textMuted, fontWeight: typography.label.fontWeight, lineHeight: typography.body.lineHeight },
  operatorProgress: { display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 6, marginTop: 14 },
  progressDot: { height: 30, borderRadius: 999, display: "grid", placeItems: "center", background: "#f1f5f9", border: "1px solid #e2e8f0", color: "#64748b", fontWeight: 1000, fontSize: 12 },
  progressDotActive: { height: 30, borderRadius: 999, display: "grid", placeItems: "center", background: "#f97316", border: "1px solid #fb923c", color: "white", fontWeight: 1000, fontSize: 12 },
  checkList: { display: "grid", gap: 8, marginTop: 14 },
  checkLine: { display: "flex", gap: 8, alignItems: "center", color: "#334155", fontWeight: 850, fontSize: 13 },
  checkOk: { width: 22, height: 22, borderRadius: 999, display: "grid", placeItems: "center", background: "#dcfce7", color: "#166534", fontWeight: 1000 },
  checkPending: { width: 22, height: 22, borderRadius: 999, display: "grid", placeItems: "center", background: "#fef3c7", color: "#92400e", fontWeight: 1000 },
  operatorWarning: { background: colors.warningSoft, border: `1px solid ${colors.warning}`, color: colors.warningDark, borderRadius: radius.md, padding: spacing.md, fontWeight: typography.label.fontWeight, marginTop: spacing.md },
  operatorInfo: { background: colors.infoSoft, border: `1px solid ${colors.info}`, color: colors.info, borderRadius: radius.md, padding: spacing.md, fontWeight: typography.label.fontWeight, marginTop: spacing.md },
  operatorMainAction: { marginTop: spacing.md, border: `1px solid ${colors.primaryBorder}`, background: colors.primarySoft, borderRadius: radius.md, padding: spacing.sm, display: "grid", gap: spacing.sm },
  operatorMainActionLabel: { color: colors.primaryHover, fontSize: typography.small.fontSize, fontWeight: typography.label.fontWeight, textTransform: "uppercase" },
  operatorPrimary: { width: "100%", minHeight: controls.minHeight, border: "none", background: colors.primary, color: colors.surface, borderRadius: radius.md, padding: controls.padding, fontWeight: typography.button.fontWeight, boxShadow: shadows.sm },
  operatorSecondary: { width: "100%", minHeight: controls.minHeight, border: `1px solid ${colors.primaryBorder}`, background: colors.surface, color: colors.primaryHover, borderRadius: radius.md, padding: controls.padding, fontWeight: typography.button.fontWeight, marginTop: spacing.sm },
  page: { minHeight: "100vh", display: "grid", gap: spacing.xl, color: colors.text, fontFamily: typography.fontFamily },
  headerLink: { minHeight: controls.minHeight, display: "inline-flex", alignItems: "center", justifyContent: "center", gap: spacing.sm, textDecoration: "none", border: `1px solid ${colors.border}`, background: colors.surface, color: colors.text, borderRadius: radius.md, padding: controls.padding, fontWeight: typography.button.fontWeight },
  hero: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, padding: 22, borderRadius: 24, background: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)", color: "white", boxShadow: "0 18px 40px rgba(15,23,42,.18)", marginBottom: 16 },
  kicker: { margin: 0, color: "#fb923c", fontSize: 12, fontWeight: 1000, textTransform: "uppercase", letterSpacing: ".08em" },
  title: { margin: "3px 0 0", fontSize: 34, fontWeight: 1000, letterSpacing: "-.03em" },
  subtitle: { margin: "8px 0 0", color: "#cbd5e1", fontWeight: 700 },
  heroActions: { display: "flex", gap: 10, flexWrap: "wrap" },
  secondaryHeroButton: { textDecoration: "none", border: "1px solid rgba(255,255,255,.22)", background: "rgba(255,255,255,.08)", color: "white", borderRadius: 14, padding: "12px 16px", fontWeight: 1000, cursor: "pointer" },
  success: { background: colors.successSoft, color: colors.successDark, border: `1px solid ${colors.success}`, borderRadius: radius.md, padding: spacing.md, fontWeight: typography.label.fontWeight },
  error: { background: colors.dangerSoft, color: colors.dangerDark, border: `1px solid ${colors.danger}`, borderRadius: radius.md, padding: spacing.md, fontWeight: typography.label.fontWeight },
  metricsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: spacing.md },
  metric: { background: colors.surface, border: `1px solid ${colors.borderSoft}`, borderRadius: radius.lg, padding: spacing.lg, display: "grid", gap: 5, boxShadow: shadows.sm },
  metricTones: { dark: { color: "#0f172a" }, ok: { color: "#047857", background: "#ecfdf5", borderColor: "#bbf7d0" }, info: { color: "#1d4ed8", background: "#eff6ff", borderColor: "#bfdbfe" }, warning: { color: "#b45309", background: "#fffbeb", borderColor: "#fde68a" }, muted: { color: "#475569", background: "#f8fafc" }, orange: { color: "#c2410c", background: "#fff7ed", borderColor: "#fed7aa" } },
  quickActionsCard: { background: colors.surface, border: `1px solid ${colors.primaryBorder}`, borderRadius: radius.lg, padding: spacing.lg, boxShadow: shadows.sm, display: "grid", gap: spacing.md },
  quickActionsTitle: { margin: "3px 0 0", color: colors.textStrong, fontSize: typography.sectionTitle.fontSize, fontWeight: typography.sectionTitle.fontWeight },
  quickActionsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 10 },
  quickAction: { minHeight: 132, border: "1px solid #e2e8f0", borderRadius: 16, background: "#f8fafc", padding: 12, display: "grid", alignContent: "space-between", gap: 10 },
  quickActionTitle: { display: "block", color: "#0f172a", fontSize: 15 },
  quickActionDetail: { margin: "5px 0 0", color: "#64748b", fontWeight: 750, fontSize: 13, lineHeight: 1.35 },
  quickActionButton: { width: "100%", border: "none", background: "#f97316", color: "white", borderRadius: 12, padding: "10px 12px", fontWeight: 1000 },
  quickActionsWarning: { margin: 0, background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", borderRadius: 14, padding: 12, fontWeight: 850 },
  quickActionsHint: { margin: 0, background: "#eff6ff", border: "1px solid #bfdbfe", color: "#1d4ed8", borderRadius: 14, padding: 12, fontWeight: 850 },
  layout: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 360px", gap: spacing.lg, alignItems: "start" },
  mainColumn: { display: "grid", gap: spacing.lg },
  card: { background: colors.surface, border: `1px solid ${colors.borderSoft}`, borderRadius: radius.lg, padding: spacing.lg, boxShadow: shadows.sm },
  cardNoPadding: { background: colors.surface, border: `1px solid ${colors.borderSoft}`, borderRadius: radius.lg, overflow: "hidden", boxShadow: shadows.sm },
  sectionHeader: { marginBottom: spacing.md },
  eyebrow: { margin: 0, color: colors.primary, fontSize: typography.small.fontSize, fontWeight: typography.label.fontWeight, textTransform: "uppercase" },
  cardTitle: { margin: "3px 0 0", fontSize: typography.sectionTitle.fontSize, fontWeight: typography.sectionTitle.fontWeight },
  muted: { color: colors.textMuted, margin: "4px 0 0", lineHeight: typography.body.lineHeight },
  itemGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(210px, 1fr))", gap: 12, alignItems: "end" },
  itemComposer: { display: "grid", gap: 12 },
  tipoSelector: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  tipoButton: { border: "1px solid #cbd5e1", background: "white", color: "#334155", borderRadius: 14, padding: "12px 14px", fontWeight: 1000, cursor: "pointer" },
  tipoButtonActive: { border: "1px solid #f97316", background: "#fff7ed", color: "#c2410c", borderRadius: 14, padding: "12px 14px", fontWeight: 1000, cursor: "pointer", boxShadow: "0 10px 22px rgba(249,115,22,.12)" },
  selectorHint: { background: "#fff7ed", border: "1px solid #fed7aa", color: "#9a3412", borderRadius: 13, padding: "10px 12px", fontWeight: 800, fontSize: 13 },
  coverageInfo: { background: "#ecfdf5", border: "1px solid #bbf7d0", color: "#047857", borderRadius: 14, padding: 12, fontWeight: 850 },
  coveragePanel: { display: "grid", gap: 12, padding: 14, border: "1px solid #86efac", borderRadius: 16, background: "#f0fdf4" },
  coverageToggle: { display: "flex", alignItems: "center", gap: 9, color: "#166534", fontWeight: 950 },
  coverageFields: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 10 },
  coverageResult: { display: "flex", justifyContent: "space-between", gap: 10, flexWrap: "wrap", paddingTop: 10, borderTop: "1px solid #bbf7d0", color: "#166534", fontWeight: 800 },
  itemsPicker: { display: "grid", gap: 10, maxHeight: 360, overflowY: "auto", paddingRight: 4 },
  tallerOption: { width: "100%", border: "1px solid #e2e8f0", background: "white", borderRadius: 16, padding: 10, display: "grid", gridTemplateColumns: "64px minmax(0, 1fr) auto", gap: 12, alignItems: "center", textAlign: "left", cursor: "pointer" },
  tallerOptionSelected: { width: "100%", border: "1px solid #f97316", background: "#fff7ed", borderRadius: 16, padding: 10, display: "grid", gridTemplateColumns: "64px minmax(0, 1fr) auto", gap: 12, alignItems: "center", textAlign: "left", cursor: "pointer", boxShadow: "0 10px 22px rgba(249,115,22,.15)" },
  optionImageBox: { width: 58, height: 58, borderRadius: 14, background: "#f8fafc", border: "1px solid #e2e8f0", display: "grid", placeItems: "center", overflow: "hidden" },
  optionBody: { minWidth: 0, display: "grid", gap: 4 },
  optionTop: { display: "flex", gap: 8, justifyContent: "space-between", alignItems: "center" },
  optionMeta: { display: "flex", gap: 8, flexWrap: "wrap", color: "#64748b", fontSize: 12, fontWeight: 800 },
  serviceBadge: { background: "#ecfdf5", color: "#047857", borderRadius: 999, padding: "5px 8px", fontSize: 12, fontWeight: 1000 },
  partBadge: { background: "#eff6ff", color: "#1d4ed8", borderRadius: 999, padding: "5px 8px", fontSize: 12, fontWeight: 1000 },
  optionPrice: { whiteSpace: "nowrap", fontSize: 15 },
  selectedItemBox: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", background: "#ecfdf5", border: "1px solid #bbf7d0", borderRadius: 16, padding: 12 },
  itemFormRow: { display: "grid", gridTemplateColumns: "160px 180px minmax(180px, 1fr)", gap: 12, alignItems: "end" },
  field: { display: "grid", gap: spacing.sm, fontSize: typography.label.fontSize, fontWeight: typography.label.fontWeight },
  label: { color: colors.text },
  input: { width: "100%", minHeight: controls.minHeight, border: `1px solid ${colors.border}`, borderRadius: radius.md, padding: controls.padding, color: colors.text, boxSizing: "border-box", background: colors.surface },
  primaryButton: { minHeight: controls.minHeight, border: "none", background: colors.primary, color: colors.surface, borderRadius: radius.md, padding: controls.padding, fontWeight: typography.button.fontWeight, cursor: "pointer", boxShadow: shadows.sm },
  secondaryButtonFull: { width: "100%", minHeight: controls.minHeight, border: `1px solid ${colors.border}`, background: colors.surface, color: colors.text, borderRadius: radius.md, padding: controls.padding, fontWeight: typography.button.fontWeight, cursor: "pointer", textAlign: "center" },
  tableHeader: { padding: 18, borderBottom: "1px solid #e2e8f0" },
  itemsList: { display: "grid", gap: 10, padding: 16 },
  itemCard: { border: "1px solid #e2e8f0", borderRadius: 18, padding: 14, display: "grid", gap: 12, background: "white" },
  itemCardMuted: { border: "1px solid #e2e8f0", borderRadius: 18, padding: 14, display: "grid", gap: 12, background: "#f8fafc", opacity: 0.78 },
  itemTop: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "start" },
  itemTitleLine: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  itemTitle: { fontSize: 16 },
  coverageSummary: { display: "grid", gap: 3, marginTop: 9, padding: "9px 10px", border: "1px solid #bbf7d0", borderRadius: 12, background: "#f0fdf4", color: "#166534", fontSize: 13, fontWeight: 800 },
  itemBottom: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", borderTop: "1px solid #f1f5f9", paddingTop: 10 },
  itemActions: { display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" },
  smallPrimary: { border: "none", background: "#0f172a", color: "white", borderRadius: 11, padding: "8px 10px", fontWeight: 900, cursor: "pointer" },
  smallSecondary: { border: "1px solid #cbd5e1", background: "white", color: "#0f172a", borderRadius: 11, padding: "8px 10px", fontWeight: 900, cursor: "pointer" },
  smallDanger: { border: "1px solid #fecaca", background: "#fff1f0", color: "#b42318", borderRadius: 11, padding: "8px 10px", fontWeight: 900, cursor: "pointer" },
  smallMuted: { color: "#64748b", fontWeight: 800 },
  sidePanel: { display: "grid", gap: 16, position: "sticky", top: 16 },
  sideTitle: { margin: "0 0 12px", fontSize: 20 },
  statusForm: { display: "grid", gap: 12 },
  billingBox: {
    display: "grid",
    gap: 10,
  },
  postventaNotice: {
    background: "#ecfdf5",
    border: "1px solid #bbf7d0",
    color: "#047857",
    borderRadius: 14,
    padding: 12,
    fontWeight: 850,
    lineHeight: 1.4,
  },
  linkButton: {
    display: "block",
    textAlign: "center",
    textDecoration: "none",
    border: "none",
    background: "#f97316",
    color: "white",
    borderRadius: 12,
    padding: "11px 12px",
    fontWeight: 1000,
    cursor: "pointer",
  },
  note: { marginTop: 12, background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", borderRadius: 14, padding: 12, fontWeight: 800 },
  noteComposer: { display: "grid", gap: 12, marginBottom: 16, padding: 14, border: "1px solid #e2e8f0", borderRadius: 16, background: "#f8fafc" },
  previousAlertsBox: { display: "grid", gap: 9, marginBottom: 14, padding: 13, border: "1px solid #fdba74", borderRadius: 15, background: "#fff7ed", color: "#9a3412" },
  previousAlertItem: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap", paddingTop: 8, borderTop: "1px solid #fed7aa", fontWeight: 800 },
  previousAlertLink: { color: "#c2410c", fontWeight: 950, textDecoration: "none", whiteSpace: "nowrap" },
  noteTextarea: { width: "100%", minHeight: 92, resize: "vertical", border: "1px solid #cbd5e1", borderRadius: 13, padding: "12px 13px", fontWeight: 700, color: "#0f172a", boxSizing: "border-box", background: "white" },
  noteComposerFooter: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" },
  noteVisibilityHint: { color: "#64748b", fontSize: 13, fontWeight: 800, flex: "1 1 260px" },
  notesList: { display: "grid", gap: 10 },
  technicalNote: { display: "grid", gap: 10, padding: 14, border: "1px solid #e2e8f0", borderRadius: 16, background: "white" },
  technicalNoteArchived: { opacity: 0.65, background: "#f8fafc" },
  technicalNoteHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap" },
  technicalNoteMeta: { color: "#64748b", fontSize: 12, fontWeight: 800 },
  technicalNoteText: { margin: 0, color: "#1e293b", fontWeight: 750, lineHeight: 1.5, whiteSpace: "pre-wrap" },
  noteBadges: { display: "flex", gap: 7, flexWrap: "wrap" },
  noteActions: { display: "flex", gap: 8, flexWrap: "wrap", paddingTop: 8, borderTop: "1px solid #f1f5f9" },
  warningText: { margin: 0, background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", borderRadius: 14, padding: 12, fontWeight: 800 },
  infoBox: { background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 14, padding: 12, display: "grid", gap: 5, color: "#64748b" },
  timeline: { display: "grid", gap: 10, maxHeight: 480, overflowY: "auto" },
  eventItem: { borderLeft: "4px solid #f97316", background: "#f8fafc", borderRadius: 14, padding: 12, display: "grid", gap: 4, color: "#334155" },
  empty: { padding: 22, color: "#64748b", fontWeight: 900 },
  emptySmall: { color: "#64748b", fontWeight: 900, background: "#f8fafc", borderRadius: 14, padding: 12 },
  stageBadge: { borderRadius: 999, padding: "7px 10px", fontWeight: 1000, fontSize: 12, whiteSpace: "nowrap", border: "1px solid transparent" },
  stageTones: { ok: { background: "#dcfce7", color: "#166534", borderColor: "#bbf7d0" }, info: { background: "#eff6ff", color: "#1d4ed8", borderColor: "#bfdbfe" }, warning: { background: "#fef3c7", color: "#92400e", borderColor: "#fde68a" }, danger: { background: "#fee2e2", color: "#991b1b", borderColor: "#fecaca" } },
  state: { padding: 24, fontWeight: 900 },

  operatorCardCompact: {
    boxShadow: "0 10px 26px rgba(249,115,22,.10)",
  },
  operatorHeaderActions: {
    display: "flex",
    gap: 8,
    alignItems: "center",
  },
  operatorToggle: {
    border: "1px solid #fed7aa",
    background: "white",
    color: "#c2410c",
    borderRadius: 999,
    padding: "7px 10px",
    fontWeight: 1000,
    cursor: "pointer",
  },
  pageMobile: {
    padding: 10,
    overflowX: "hidden",
  },
  heroMobile: {
    display: "grid",
    gridTemplateColumns: "1fr",
    alignItems: "stretch",
    padding: 16,
    borderRadius: 20,
    gap: 14,
  },
  heroActionsMobile: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    width: "100%",
  },
  metricsGridMobile: {
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
  },
  layoutMobile: {
    gridTemplateColumns: "1fr",
    gap: 12,
  },
  mainColumnMobile: {
    gap: 12,
  },
  sidePanelMobile: {
    position: "static",
    display: "grid",
    gap: 12,
    width: "100%",
    minWidth: 0,
  },
  tipoSelectorMobile: {
    gridTemplateColumns: "1fr",
  },
  itemFormRowMobile: {
    gridTemplateColumns: "1fr",
    gap: 10,
  },
};
