import { colors, controls, radius, shadows, spacing, typography } from "../../../theme";

export const styles = {
  operatorCard: { border: `1px solid ${colors.borderSoft}`, background: colors.surface },
  operatorHeader: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "start" },
  operatorStep: { background: colors.topbar, color: colors.surface, borderRadius: radius.pill, padding: "7px 10px", fontWeight: typography.label.fontWeight, fontSize: typography.small.fontSize },
  operatorText: { margin: "8px 0 0", color: colors.textMuted, fontWeight: typography.label.fontWeight, lineHeight: typography.body.lineHeight },
  operatorProgress: { display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 6, marginTop: 14 },
  operatorProgressLine: { display: "grid", gridTemplateColumns: "repeat(6, minmax(0, 1fr))", gap: 8, marginTop: 14, padding: "12px 0 2px", borderTop: `1px solid ${colors.borderSoft}` },
  operatorProgressStep: { display: "grid", justifyItems: "center", gap: 6, color: colors.textMuted, fontSize: 11, fontWeight: 700, textAlign: "center", minWidth: 0 },
  progressDot: { height: 30, borderRadius: 999, display: "grid", placeItems: "center", background: "#f1f5f9", border: "1px solid #e2e8f0", color: "#64748b", fontWeight: 800, fontSize: 12 },
  progressDotActive: { height: 30, borderRadius: 999, display: "grid", placeItems: "center", background: "#f97316", border: "1px solid #fb923c", color: "white", fontWeight: 800, fontSize: 12 },
  operatorStatsBox: { display: "grid", gridTemplateColumns: "repeat(5, minmax(0, 1fr))", gap: 8, marginTop: 14, padding: 12, border: `1px solid ${colors.borderSoft}`, background: "#f8fafc", borderRadius: radius.md },
  operatorStat: { minWidth: 0, display: "grid", gap: 4, justifyItems: "center", textAlign: "center", color: colors.textMuted, fontSize: 12, fontWeight: 700 },
  operatorStatIcon: { width: 12, height: 12, borderRadius: 999, display: "block", background: colors.textMuted },
  operatorStatTones: {
    ok: { icon: { background: colors.success } },
    warning: { icon: { background: colors.warning } },
    info: { icon: { background: colors.info } },
    danger: { icon: { background: colors.danger } },
    dark: { icon: { background: colors.textStrong } },
  },
  operatorRecommendation: { marginTop: 14, display: "grid", gridTemplateColumns: "34px minmax(0, 1fr)", gap: 10, alignItems: "start", padding: 12, border: `1px solid ${colors.borderSoft}`, background: colors.surface, borderRadius: radius.md, color: colors.text },
  operatorRecommendationIcon: { width: 28, height: 28, borderRadius: 999, display: "grid", placeItems: "center", background: colors.primarySoft, color: colors.primary, fontWeight: 800 },
  operatorRecommendationText: { margin: "4px 0 0", color: colors.textMuted, fontWeight: 800, lineHeight: 1.35 },
  checkList: { display: "grid", gap: 8, marginTop: 14 },
  checkLine: { display: "flex", gap: 8, alignItems: "center", color: "#334155", fontWeight: 700, fontSize: 13 },
  checkOk: { width: 22, height: 22, borderRadius: 999, display: "grid", placeItems: "center", background: "#dcfce7", color: "#166534", fontWeight: 800 },
  checkPending: { width: 22, height: 22, borderRadius: 999, display: "grid", placeItems: "center", background: "#fef3c7", color: "#92400e", fontWeight: 800 },
  operatorWarning: { background: colors.warningSoft, border: `1px solid ${colors.warning}`, color: colors.warningDark, borderRadius: radius.md, padding: spacing.md, fontWeight: typography.label.fontWeight, marginTop: spacing.md },
  operatorInfo: { background: colors.infoSoft, border: `1px solid ${colors.info}`, color: colors.info, borderRadius: radius.md, padding: spacing.md, fontWeight: typography.label.fontWeight, marginTop: spacing.md },
  operatorMainAction: { marginTop: spacing.md, border: `1px solid ${colors.primaryBorder}`, background: colors.primarySoft, borderRadius: radius.md, padding: spacing.sm, display: "grid", gap: spacing.sm },
  operatorMainActionLabel: { color: colors.primaryHover, fontSize: typography.small.fontSize, fontWeight: typography.label.fontWeight, textTransform: "uppercase" },
  operatorPrimary: { width: "100%", minHeight: controls.minHeight, border: "none", background: colors.primary, color: colors.surface, borderRadius: radius.md, padding: controls.padding, fontWeight: typography.button.fontWeight, boxShadow: shadows.sm },
  operatorSecondary: { width: "100%", minHeight: controls.minHeight, border: `1px solid ${colors.primaryBorder}`, background: colors.surface, color: colors.primaryHover, borderRadius: radius.md, padding: controls.padding, fontWeight: typography.button.fontWeight, marginTop: spacing.sm },
  page: { minHeight: "100vh", display: "grid", gap: spacing.xl, color: colors.text, fontFamily: typography.fontFamily },
  headerLink: { minHeight: controls.minHeight, display: "inline-flex", alignItems: "center", justifyContent: "center", gap: spacing.sm, textDecoration: "none", border: `1px solid ${colors.border}`, background: colors.surface, color: colors.text, borderRadius: radius.md, padding: controls.padding, fontWeight: typography.button.fontWeight },
  hero: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, padding: 22, borderRadius: 24, background: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)", color: "white", boxShadow: "0 18px 40px rgba(15,23,42,.18)", marginBottom: 16 },
  kicker: { margin: 0, color: "#fb923c", fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: ".08em" },
  title: { margin: "3px 0 0", fontSize: 34, fontWeight: 800, letterSpacing: "-.03em" },
  subtitle: { margin: "8px 0 0", color: "#cbd5e1", fontWeight: 700 },
  heroActions: { display: "flex", gap: 10, flexWrap: "wrap" },
  secondaryHeroButton: { textDecoration: "none", border: "1px solid rgba(255,255,255,.22)", background: "rgba(255,255,255,.08)", color: "white", borderRadius: 14, padding: "12px 16px", fontWeight: 800, cursor: "pointer" },
  success: { background: colors.successSoft, color: colors.successDark, border: `1px solid ${colors.success}`, borderRadius: radius.md, padding: spacing.md, fontWeight: typography.label.fontWeight },
  error: { background: colors.dangerSoft, color: colors.dangerDark, border: `1px solid ${colors.danger}`, borderRadius: radius.md, padding: spacing.md, fontWeight: typography.label.fontWeight },
  compactHeader: { background: colors.surface, border: `1px solid ${colors.borderSoft}`, borderRadius: radius.lg, padding: spacing.lg, boxShadow: shadows.sm, display: "grid", gap: spacing.lg },
  compactHeaderTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: spacing.lg, flexWrap: "wrap" },
  compactTitleGroup: { display: "grid", gap: 5, minWidth: 0, flex: "1 1 420px" },
  compactTitleRow: { display: "flex", alignItems: "center", gap: spacing.sm, flexWrap: "wrap" },
  compactTitle: { margin: 0, color: colors.textStrong, fontSize: 32, fontWeight: 800, lineHeight: 1.05 },
  compactSubtitle: { margin: 0, color: colors.textMuted, fontWeight: 800 },
  compactNextBadge: { border: `1px solid ${colors.primaryBorder}`, background: colors.primarySoft, color: colors.primaryHover, borderRadius: radius.pill, padding: "7px 10px", fontSize: typography.small.fontSize, fontWeight: typography.label.fontWeight },
  compactHeaderActions: { display: "flex", gap: spacing.sm, flexWrap: "wrap", justifyContent: "flex-end" },
  compactFactsGrid: { display: "grid", gridTemplateColumns: "1.1fr 1.3fr minmax(240px, 1.8fr) minmax(150px, .7fr)", gap: spacing.xl, alignItems: "start", paddingTop: spacing.sm, borderTop: `1px solid ${colors.borderSoft}` },
  compactFact: { minWidth: 0, display: "grid", gap: 5, background: "transparent", border: "none", borderRadius: 0, padding: 0 },
  compactFactAccent: { minWidth: 0, display: "grid", gap: 5, background: "transparent", border: "none", borderRadius: 0, padding: 0 },
  compactFactLabel: { color: colors.textMuted, fontSize: typography.small.fontSize, fontWeight: typography.label.fontWeight, textTransform: "uppercase" },
  compactFactValue: { minWidth: 0, color: colors.textStrong, fontWeight: 800, lineHeight: 1.25 },
  compactFactStrong: { minWidth: 0, color: colors.textStrong, fontWeight: 800, lineHeight: 1.25 },
  compactObservation: { margin: 0, color: colors.textMuted, fontWeight: 800, lineHeight: typography.body.lineHeight, background: "#f8fafc", borderRadius: radius.md, padding: spacing.md },
  metricsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: spacing.md },
  metric: { background: colors.surface, border: `1px solid ${colors.borderSoft}`, borderRadius: radius.lg, padding: spacing.lg, display: "grid", gap: 5, boxShadow: shadows.sm },
  metricTones: { dark: { color: "#0f172a" }, ok: { color: "#047857", background: "#ecfdf5", borderColor: "#bbf7d0" }, info: { color: "#1d4ed8", background: "#eff6ff", borderColor: "#bfdbfe" }, warning: { color: "#b45309", background: "#fffbeb", borderColor: "#fde68a" }, muted: { color: "#475569", background: "#f8fafc" }, orange: { color: "#c2410c", background: "#fff7ed", borderColor: "#fed7aa" } },
  quickActionsCard: { background: colors.surface, border: `1px solid ${colors.primaryBorder}`, borderRadius: radius.lg, padding: spacing.lg, boxShadow: shadows.sm, display: "grid", gap: spacing.md },
  quickActionsTitle: { margin: "3px 0 0", color: colors.textStrong, fontSize: typography.sectionTitle.fontSize, fontWeight: typography.sectionTitle.fontWeight },
  quickActionsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 10 },
  quickAction: { minHeight: 132, border: "1px solid #e2e8f0", borderRadius: 16, background: "#f8fafc", padding: 12, display: "grid", alignContent: "space-between", gap: 10 },
  quickActionTitle: { display: "block", color: "#0f172a", fontSize: 15 },
  quickActionDetail: { margin: "5px 0 0", color: "#64748b", fontWeight: 700, fontSize: 13, lineHeight: 1.35 },
  quickActionButton: { width: "100%", border: "none", background: "#f97316", color: "white", borderRadius: 12, padding: "10px 12px", fontWeight: 800 },
  quickActionsWarning: { margin: 0, background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", borderRadius: 14, padding: 12, fontWeight: 700 },
  quickActionsHint: { margin: 0, background: "#eff6ff", border: "1px solid #bfdbfe", color: "#1d4ed8", borderRadius: 14, padding: 12, fontWeight: 700 },
  layout: { display: "grid", gridTemplateColumns: "minmax(0, 7fr) minmax(340px, 3fr)", gap: spacing.lg, alignItems: "start" },
  mainColumn: { display: "grid", gap: spacing.lg },
  card: { background: colors.surface, border: `1px solid ${colors.borderSoft}`, borderRadius: radius.lg, padding: spacing.lg, boxShadow: shadows.sm },
  cardNoPadding: { background: colors.surface, border: `1px solid ${colors.borderSoft}`, borderRadius: radius.lg, overflow: "hidden", boxShadow: shadows.sm },
  collapsiblePanel: { background: colors.surface, border: `1px solid ${colors.borderSoft}`, borderRadius: radius.lg, boxShadow: shadows.sm, overflow: "hidden" },
  collapsibleSummary: { cursor: "pointer", listStyle: "none", display: "flex", justifyContent: "space-between", alignItems: "center", gap: spacing.md, padding: spacing.lg, color: colors.textStrong, fontSize: typography.sectionTitle.fontSize },
  collapsibleTitleGroup: { display: "grid", gap: 4, minWidth: 0 },
  collapsibleHint: { color: colors.primary, fontSize: typography.small.fontSize, fontWeight: typography.label.fontWeight },
  collapsibleBody: { padding: `0 ${spacing.lg} ${spacing.lg}` },
  drawerLayer: { position: "fixed", inset: 0, zIndex: 80, display: "grid", justifyItems: "end", background: "rgba(15, 23, 42, .28)" },
  drawerBackdrop: { position: "fixed", inset: 0, border: "none", background: "transparent", cursor: "pointer" },
  itemDrawer: { position: "relative", zIndex: 1, width: "min(560px, calc(100vw - 24px))", height: "100vh", background: colors.surface, boxShadow: "-24px 0 50px rgba(15,23,42,.22)", borderLeft: `1px solid ${colors.borderSoft}`, display: "grid", gridTemplateRows: "auto minmax(0, 1fr)" },
  itemDrawerHeader: { padding: spacing.lg, borderBottom: `1px solid ${colors.borderSoft}`, display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: spacing.md, background: "#fffaf5" },
  itemDrawerBody: { minHeight: 0, overflowY: "auto", padding: spacing.lg, display: "grid", alignContent: "start", gap: spacing.md },
  drawerCloseButton: { width: 42, height: 42, borderRadius: radius.md, border: `1px solid ${colors.border}`, background: colors.surface, color: colors.textStrong, fontSize: 28, lineHeight: 1, fontWeight: 700, cursor: "pointer", display: "grid", placeItems: "center", flex: "0 0 auto" },
  secondaryInfoPanel: { order: 3 },
  secondaryTabsShell: { background: colors.surface, border: `1px solid ${colors.borderSoft}`, borderRadius: radius.lg, boxShadow: shadows.sm, overflow: "hidden" },
  secondaryTabsNav: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", borderBottom: `1px solid ${colors.borderSoft}`, background: "#f8fafc" },
  secondaryTab: { minHeight: 50, display: "inline-flex", alignItems: "center", justifyContent: "center", color: colors.textMuted, fontWeight: 700, borderBottom: "2px solid transparent" },
  secondaryTabActive: { minHeight: 50, display: "inline-flex", alignItems: "center", justifyContent: "center", color: colors.textStrong, fontWeight: 800, borderBottom: `2px solid ${colors.primary}`, background: colors.surface },
  secondaryTabsContent: { display: "grid", gap: spacing.md, padding: spacing.md },
  sectionHeader: { marginBottom: spacing.md },
  eyebrow: { margin: 0, color: colors.primary, fontSize: typography.small.fontSize, fontWeight: typography.label.fontWeight, textTransform: "uppercase" },
  cardTitle: { margin: "3px 0 0", fontSize: typography.sectionTitle.fontSize, fontWeight: typography.sectionTitle.fontWeight },
  muted: { color: colors.textMuted, margin: "4px 0 0", lineHeight: typography.body.lineHeight },
  itemGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(210px, 1fr))", gap: 12, alignItems: "end" },
  itemComposer: { display: "grid", gap: 12 },
  tipoSelector: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  tipoButton: { border: "1px solid #cbd5e1", background: "white", color: "#334155", borderRadius: 14, padding: "12px 14px", fontWeight: 800, cursor: "pointer" },
  tipoButtonActive: { border: "1px solid #f97316", background: "#fff7ed", color: "#c2410c", borderRadius: 14, padding: "12px 14px", fontWeight: 800, cursor: "pointer", boxShadow: "0 10px 22px rgba(249,115,22,.12)" },
  selectorHint: { background: "#fff7ed", border: "1px solid #fed7aa", color: "#9a3412", borderRadius: 13, padding: "10px 12px", fontWeight: 800, fontSize: 13 },
  coverageInfo: { background: "#ecfdf5", border: "1px solid #bbf7d0", color: "#047857", borderRadius: 14, padding: 12, fontWeight: 700 },
  coveragePanel: { display: "grid", gap: 12, padding: 14, border: "1px solid #86efac", borderRadius: 16, background: "#f0fdf4" },
  coverageToggle: { display: "flex", alignItems: "center", gap: 9, color: "#166534", fontWeight: 800 },
  coverageFields: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 10 },
  coverageResult: { display: "flex", justifyContent: "space-between", gap: 10, flexWrap: "wrap", paddingTop: 10, borderTop: "1px solid #bbf7d0", color: "#166534", fontWeight: 800 },
  itemsPicker: { display: "grid", gap: 10, maxHeight: 300, overflowY: "auto", paddingRight: 4 },
  tallerOption: { width: "100%", border: "1px solid #e2e8f0", background: "white", borderRadius: 16, padding: 12, display: "grid", gridTemplateColumns: "64px minmax(0, 1fr)", gap: 12, alignItems: "center", textAlign: "left", cursor: "pointer" },
  tallerOptionSelected: { width: "100%", border: "1px solid #f97316", background: "#fff7ed", borderRadius: 16, padding: 12, display: "grid", gridTemplateColumns: "64px minmax(0, 1fr)", gap: 12, alignItems: "center", textAlign: "left", cursor: "pointer", boxShadow: "0 10px 22px rgba(249,115,22,.15)" },
  optionImageBox: { width: 58, height: 58, borderRadius: 14, background: "#f8fafc", border: "1px solid #e2e8f0", display: "grid", placeItems: "center", overflow: "hidden" },
  optionBody: { minWidth: 0, display: "grid", gap: 4 },
  optionTop: { display: "flex", gap: 8, justifyContent: "space-between", alignItems: "flex-start" },
  optionMeta: { display: "flex", gap: 8, flexWrap: "wrap", color: "#64748b", fontSize: 12, fontWeight: 800 },
  serviceBadge: { background: "#ecfdf5", color: "#047857", borderRadius: 999, padding: "5px 8px", fontSize: 12, fontWeight: 800 },
  partBadge: { background: "#eff6ff", color: "#1d4ed8", borderRadius: 999, padding: "5px 8px", fontSize: 12, fontWeight: 800 },
  optionPrice: { whiteSpace: "nowrap", fontSize: 15, marginLeft: 8 },
  selectedItemBox: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", background: "#ecfdf5", border: "1px solid #bbf7d0", borderRadius: 16, padding: 12 },
  itemFormRow: { display: "grid", gridTemplateColumns: "1fr", gap: 12, alignItems: "stretch" },
  field: { display: "grid", gap: spacing.sm, fontSize: typography.label.fontSize, fontWeight: typography.label.fontWeight },
  label: { color: colors.text },
  input: { width: "100%", minHeight: controls.minHeight, border: `1px solid ${colors.border}`, borderRadius: radius.md, padding: controls.padding, color: colors.text, boxSizing: "border-box", background: colors.surface },
  primaryButton: { minHeight: controls.minHeight, border: "none", background: colors.primary, color: colors.surface, borderRadius: radius.md, padding: controls.padding, fontWeight: typography.button.fontWeight, cursor: "pointer", boxShadow: shadows.sm },
  secondaryButtonFull: { width: "100%", minHeight: controls.minHeight, border: `1px solid ${colors.border}`, background: colors.surface, color: colors.text, borderRadius: radius.md, padding: controls.padding, fontWeight: typography.button.fontWeight, cursor: "pointer", textAlign: "center" },
  tableHeader: { padding: 18, borderBottom: "1px solid #e2e8f0", display: "grid", gap: 12 },
  workCounters: { display: "flex", flexWrap: "wrap", gap: 8 },
  workCounter: { display: "inline-flex", alignItems: "center", gap: 6, border: "1px solid #e2e8f0", background: "#f8fafc", color: "#475569", borderRadius: 999, padding: "7px 10px", fontSize: 12, fontWeight: 700 },
  workToolbar: { display: "flex", flexWrap: "wrap", gap: 10, marginTop: 14 },
  workActionPrimary: { minHeight: 42, border: "none", background: colors.primary, color: colors.surface, borderRadius: radius.md, padding: "10px 14px", fontWeight: typography.button.fontWeight, cursor: "pointer", boxShadow: shadows.sm },
  workActionSecondary: { minHeight: 42, border: `1px solid ${colors.border}`, background: colors.surface, color: colors.text, borderRadius: radius.md, padding: "10px 14px", fontWeight: typography.button.fontWeight, cursor: "pointer" },
  workActionDanger: { minHeight: 42, border: `1px solid ${colors.danger}`, background: colors.dangerSoft, color: colors.dangerDark, borderRadius: radius.md, padding: "10px 14px", fontWeight: typography.button.fontWeight, cursor: "pointer" },
  workActionFinish: { minHeight: 42, border: "none", background: colors.success, color: colors.surface, borderRadius: radius.md, padding: "10px 14px", fontWeight: typography.button.fontWeight, cursor: "pointer", boxShadow: shadows.sm },
  workTableWrap: { overflowX: "auto" },
  workTable: { width: "100%", borderCollapse: "collapse", minWidth: 820, tableLayout: "fixed" },
  workTh: { padding: "12px 14px", borderBottom: "1px solid #e2e8f0", background: "#f8fafc", color: "#475569", textAlign: "left", fontSize: 12, fontWeight: 800, textTransform: "uppercase", whiteSpace: "nowrap" },
  workTr: { borderBottom: "1px solid #eef2f7", background: colors.surface },
  workTrMuted: { borderBottom: "1px solid #eef2f7", background: "#f8fafc", opacity: 0.72 },
  workTd: { padding: "13px 14px", verticalAlign: "top", color: colors.text, fontWeight: 800 },
  workItemTd: { padding: "13px 14px", verticalAlign: "top", color: colors.text, fontWeight: 800, width: "44%" },
  workCompactTd: { padding: "13px 10px", verticalAlign: "top", color: colors.text, fontWeight: 700, whiteSpace: "nowrap" },
  workPriceTd: { padding: "13px 10px", verticalAlign: "top", color: colors.text, fontWeight: 700, whiteSpace: "nowrap" },
  workActionsTd: { padding: "13px 10px", verticalAlign: "top", display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end", minWidth: 160 },
  workCoverage: { display: "block", marginTop: 5, color: colors.successDark, fontWeight: 700 },
  workUnitPrice: { display: "block", marginTop: 3, color: "#64748b", fontWeight: 800, fontSize: 12 },
  workBoard: { background: colors.surface, border: `1px solid ${colors.borderSoft}`, borderRadius: radius.lg, overflow: "hidden", boxShadow: shadows.sm },
  workBoardHeader: { padding: spacing.lg, borderBottom: `1px solid ${colors.borderSoft}`, display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: spacing.md, flexWrap: "wrap" },
  workBoardTitle: { margin: 0, color: colors.textStrong, fontSize: typography.sectionTitle.fontSize, fontWeight: typography.sectionTitle.fontWeight },
  workGroups: { display: "grid" },
  workGroup: { borderLeft: "4px solid #f97316", borderBottom: `1px solid ${colors.borderSoft}`, background: colors.surface },
  workGroupMuted: { opacity: 0.72 },
  workGroupTones: {
    pending: { borderLeftColor: "#f97316", background: "#fffaf5" },
    approved: { borderLeftColor: "#22c55e", background: "#fbfffd" },
    executed: { borderLeftColor: "#2563eb", background: "#f8fbff" },
    cancelled: { borderLeftColor: "#ef4444", background: "#fffafa" },
  },
  workGroupHeader: { padding: "14px 16px 10px", display: "flex", justifyContent: "space-between", alignItems: "center", gap: spacing.md, flexWrap: "wrap" },
  workGroupTitle: { display: "inline-flex", alignItems: "center", gap: 10, color: colors.textStrong, fontWeight: 800 },
  workGroupDot: { width: 9, height: 9, borderRadius: 999, background: "currentColor" },
  selectAllLabel: { display: "inline-flex", alignItems: "center", gap: 8, color: colors.text, fontWeight: 700, fontSize: 13 },
  workGroupTable: { display: "grid", overflowX: "auto" },
  workGroupHead: { display: "grid", gridTemplateColumns: "minmax(260px, 1.65fr) 104px 70px 120px 110px minmax(170px, .9fr)", gap: 12, alignItems: "center", padding: "9px 16px", borderTop: `1px solid ${colors.borderSoft}`, borderBottom: `1px solid ${colors.borderSoft}`, color: colors.textMuted, fontSize: 11, fontWeight: 800, textTransform: "uppercase", minWidth: 820 },
  workGroupHeadSelectable: { display: "grid", gridTemplateColumns: "26px minmax(260px, 1.65fr) 104px 70px 120px 110px minmax(170px, .9fr)", gap: 12, alignItems: "center", padding: "9px 16px", borderTop: `1px solid ${colors.borderSoft}`, borderBottom: `1px solid ${colors.borderSoft}`, color: colors.textMuted, fontSize: 11, fontWeight: 800, textTransform: "uppercase", minWidth: 860 },
  workRow: { display: "grid", gridTemplateColumns: "minmax(260px, 1.65fr) 104px 70px 120px 110px minmax(170px, .9fr)", gap: 12, alignItems: "center", padding: "12px 16px", borderBottom: `1px solid ${colors.borderSoft}`, color: colors.text, minWidth: 820 },
  workRowSelectable: { display: "grid", gridTemplateColumns: "26px minmax(260px, 1.65fr) 104px 70px 120px 110px minmax(170px, .9fr)", gap: 12, alignItems: "center", padding: "12px 16px", borderBottom: `1px solid ${colors.borderSoft}`, color: colors.text, minWidth: 860 },
  workCheckbox: { width: 18, height: 18 },
  workRowItem: { minWidth: 0, display: "grid", gap: 3, fontWeight: 700, lineHeight: 1.25 },
  workRowText: { fontWeight: 700 },
  workRowPrice: { display: "grid", gap: 2, fontWeight: 800 },
  workRowActions: { display: "flex", gap: 8, justifyContent: "flex-end", flexWrap: "wrap" },
  typeBadgePart: { justifySelf: "start", borderRadius: 999, padding: "6px 9px", background: "#eff6ff", color: "#1d4ed8", border: "1px solid #bfdbfe", fontSize: 12, fontWeight: 800 },
  typeBadgeService: { justifySelf: "start", borderRadius: 999, padding: "6px 9px", background: "#fff7ed", color: "#c2410c", border: "1px solid #fed7aa", fontSize: 12, fontWeight: 800 },
  groupActions: { display: "flex", gap: 12, flexWrap: "wrap", padding: "12px 16px", borderTop: `1px solid ${colors.borderSoft}` },
  addWorkCta: { width: "100%", border: "1px dashed #bfdbfe", background: "#fbfdff", color: colors.primary, padding: "18px 16px", display: "grid", gap: 4, justifyItems: "center", fontWeight: 800, cursor: "pointer" },
  otSummaryGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: spacing.md },
  itemsList: { display: "grid", gap: 10, padding: 16 },
  itemCard: { border: "1px solid #e2e8f0", borderRadius: 18, padding: 14, display: "grid", gap: 12, background: "white" },
  itemCardMuted: { border: "1px solid #e2e8f0", borderRadius: 18, padding: 14, display: "grid", gap: 12, background: "#f8fafc", opacity: 0.78 },
  itemTop: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "start" },
  itemTitleLine: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  itemTitle: { fontSize: 16 },
  coverageSummary: { display: "grid", gap: 3, marginTop: 9, padding: "9px 10px", border: "1px solid #bbf7d0", borderRadius: 12, background: "#f0fdf4", color: "#166534", fontSize: 13, fontWeight: 800 },
  itemBottom: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", borderTop: "1px solid #f1f5f9", paddingTop: 10 },
  itemActions: { display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" },
  smallPrimary: { border: "none", background: colors.primary, color: "white", borderRadius: 11, padding: "8px 10px", fontWeight: 700, cursor: "pointer" },
  smallSecondary: { border: "1px solid #cbd5e1", background: "white", color: "#0f172a", borderRadius: 11, padding: "8px 10px", fontWeight: 700, cursor: "pointer" },
  smallDanger: { border: "1px solid #fecaca", background: "#fff1f0", color: "#b42318", borderRadius: 11, padding: "8px 10px", fontWeight: 700, cursor: "pointer" },
  smallMuted: { color: "#64748b", fontWeight: 800 },
  inlineError: { background: "#fff1f0", color: "#b42318", border: "1px solid #fecaca", borderRadius: 12, padding: "10px 12px", fontWeight: 700, fontSize: 13 },
  sidePanel: { display: "grid", gap: 16, position: "sticky", top: 16 },
  sideTitle: { margin: "0 0 12px", fontSize: 20 },
  statusForm: { display: "grid", gap: 12 },
  billingBox: {
    display: "grid",
    gap: 10,
  },
  postventaNotice: {
    background: "#ecfdf5",
    border: "1px solid #bbf7d0",
    color: "#047857",
    borderRadius: 14,
    padding: 12,
    fontWeight: 700,
    lineHeight: 1.4,
  },
  linkButton: {
    display: "block",
    textAlign: "center",
    textDecoration: "none",
    border: "none",
    background: "#f97316",
    color: "white",
    borderRadius: 12,
    padding: "11px 12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  note: { marginTop: 12, background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", borderRadius: 14, padding: 12, fontWeight: 800 },
  noteComposer: { display: "grid", gap: 12, marginBottom: 16, padding: 14, border: "1px solid #e2e8f0", borderRadius: 16, background: "#f8fafc" },
  previousAlertsBox: { display: "grid", gap: 9, marginBottom: 14, padding: 13, border: "1px solid #fdba74", borderRadius: 15, background: "#fff7ed", color: "#9a3412" },
  previousAlertItem: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap", paddingTop: 8, borderTop: "1px solid #fed7aa", fontWeight: 800 },
  previousAlertLink: { color: "#c2410c", fontWeight: 800, textDecoration: "none", whiteSpace: "nowrap" },
  noteTextarea: { width: "100%", minHeight: 92, resize: "vertical", border: "1px solid #cbd5e1", borderRadius: 13, padding: "12px 13px", fontWeight: 700, color: "#0f172a", boxSizing: "border-box", background: "white" },
  noteComposerFooter: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" },
  noteVisibilityHint: { color: "#64748b", fontSize: 13, fontWeight: 800, flex: "1 1 260px" },
  notesList: { display: "grid", gap: 10 },
  technicalNote: { display: "grid", gap: 10, padding: 14, border: "1px solid #e2e8f0", borderRadius: 16, background: "white" },
  technicalNoteArchived: { opacity: 0.65, background: "#f8fafc" },
  technicalNoteHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap" },
  technicalNoteMeta: { color: "#64748b", fontSize: 12, fontWeight: 800 },
  technicalNoteText: { margin: 0, color: "#1e293b", fontWeight: 700, lineHeight: 1.5, whiteSpace: "pre-wrap" },
  noteBadges: { display: "flex", gap: 7, flexWrap: "wrap" },
  noteActions: { display: "flex", gap: 8, flexWrap: "wrap", paddingTop: 8, borderTop: "1px solid #f1f5f9" },
  warningText: { margin: 0, background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", borderRadius: 14, padding: 12, fontWeight: 800 },
  infoBox: { background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 14, padding: 12, display: "grid", gap: 5, color: "#64748b" },
  timeline: { display: "grid", gap: 10, maxHeight: 480, overflowY: "auto" },
  eventItem: { borderLeft: "4px solid #f97316", background: "#f8fafc", borderRadius: 14, padding: 12, display: "grid", gap: 4, color: "#334155" },
  empty: { padding: 22, color: "#64748b", fontWeight: 700 },
  emptySmall: { color: "#64748b", fontWeight: 700, background: "#f8fafc", borderRadius: 14, padding: 12 },
  stageBadge: { borderRadius: 999, padding: "7px 10px", fontWeight: 800, fontSize: 12, whiteSpace: "nowrap", border: "1px solid transparent" },
  stageTones: { ok: { background: "#dcfce7", color: "#166534", borderColor: "#bbf7d0" }, info: { background: "#eff6ff", color: "#1d4ed8", borderColor: "#bfdbfe" }, warning: { background: "#fef3c7", color: "#92400e", borderColor: "#fde68a" }, danger: { background: "#fee2e2", color: "#991b1b", borderColor: "#fecaca" } },
  state: { padding: 24, fontWeight: 700 },

  operatorCardCompact: {
    boxShadow: "0 10px 26px rgba(249,115,22,.10)",
  },
  operatorHeaderActions: {
    display: "flex",
    gap: 8,
    alignItems: "center",
  },
  operatorToggle: {
    border: "1px solid #fed7aa",
    background: "white",
    color: "#c2410c",
    borderRadius: 999,
    padding: "7px 10px",
    fontWeight: 800,
    cursor: "pointer",
  },
  pageMobile: {
    padding: 10,
    overflowX: "hidden",
  },
  heroMobile: {
    display: "grid",
    gridTemplateColumns: "1fr",
    alignItems: "stretch",
    padding: 16,
    borderRadius: 20,
    gap: 14,
  },
  heroActionsMobile: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    width: "100%",
  },
  metricsGridMobile: {
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
  },
  layoutMobile: {
    gridTemplateColumns: "1fr",
    gap: 12,
  },
  mainColumnMobile: {
    gap: 12,
    order: 2,
  },
  sidePanelMobile: {
    position: "static",
    display: "grid",
    gap: 12,
    width: "100%",
    minWidth: 0,
    order: 1,
  },
  tipoSelectorMobile: {
    gridTemplateColumns: "1fr",
  },
  itemFormRowMobile: {
    gridTemplateColumns: "1fr",
    gap: 10,
  },
  itemDrawerMobile: {
    width: "100vw",
    height: "100vh",
    borderLeft: "none",
  },
};
