from decimal import Decimal

VENTA_ESTADO_CREADA = "creada"
VENTA_ESTADO_PAGADA_PARCIAL = "pagada_parcial"
VENTA_ESTADO_PAGADA_TOTAL = "pagada_total"
VENTA_ESTADO_ENTREGADA = "entregada"
VENTA_ESTADO_ANULADA = "anulada"

#ENTIDADES
AUDITORIA_ENTIDAD_VENTA = "venta"
AUDITORIA_ENTIDAD_PAGO = "pago"
AUDITORIA_ENTIDAD_CAJA = "caja"

#ACCION DE VENTA
AUDITORIA_ACCION_VENTA_CREADA = "venta_creada"
AUDITORIA_ACCION_VENTA_ENTREGADA = "venta_entregada"
AUDITORIA_ACCION_VENTA_ANULADA = "anular_venta"

#ACCION DE PAGO 
AUDITORIA_ACCION_PAGO_REGISTRADO = "pago_registrado"
AUDITORIA_ACCION_PAGO_REVERTIDO = "revertir_pago"

#ACCION DE CAJA 
AUDITORIA_ACCION_CAJA_EGRESO = "egreso_caja"
AUDITORIA_ACCION_CAJA_CERRADA = "cerrar_caja"
AUDITORIA_ACCION_CAJA_AJUSTE = "ajuste_caja"


CREDITO_ESTADO_ABIERTO = "abierto"
CREDITO_ESTADO_APLICADO_PARCIAL = "aplicado_parcial"
CREDITO_ESTADO_APLICADO_TOTAL = "aplicado_total"

CREDITO_MOVIMIENTO_GENERADO = "credito_generado"
CREDITO_MOVIMIENTO_APLICACION_VENTA = "aplicacion_a_venta"

ORIGEN_VENTA = "venta"

MEDIOS_PAGO_VALIDOS = {
    "efectivo",
    "transferencia",
    "mercadopago",
    "tarjeta",
}

ORIGENES_PAGO_VALIDOS = {
    "venta",
    "reserva",
    "orden_taller",
    "deuda_cliente",
}

DECIMAL_ZERO = Decimal("0")

PAGO_ESTADO_REVERTIDO = "revertido"

# TALLER

ORDEN_TALLER_ESTADO_INGRESADA = "ingresada"
ORDEN_TALLER_ESTADO_PRESUPUESTADA = "presupuestada"
ORDEN_TALLER_ESTADO_EN_REPARACION = "en_reparacion"
ORDEN_TALLER_ESTADO_TERMINADA = "terminada"

ORDEN_TALLER_EVENTO_CREADA = "creada"
ORDEN_TALLER_EVENTO_CAMBIO_ESTADO = "cambio_estado"
ORDEN_TALLER_EVENTO_AGREGADO_ITEM = "agregado_item"

# AUDITORIA - ENTIDADES
AUDITORIA_ENTIDAD_VENTA = "venta"
AUDITORIA_ENTIDAD_PAGO = "pago"
AUDITORIA_ENTIDAD_CAJA = "caja"

# AUDITORIA - ACCIONES
AUDITORIA_ACCION_VENTA_CREADA = "venta_creada"
AUDITORIA_ACCION_VENTA_ENTREGADA = "venta_entregada"
AUDITORIA_ACCION_VENTA_ANULADA = "anular_venta"

AUDITORIA_ACCION_PAGO_REGISTRADO = "pago_registrado"
AUDITORIA_ACCION_PAGO_REVERTIDO = "revertir_pago"

AUDITORIA_ACCION_CAJA_EGRESO = "egreso_caja"
AUDITORIA_ACCION_CAJA_CERRADA = "cerrar_caja"
AUDITORIA_ACCION_CAJA_AJUSTE = "ajuste_caja"

#CAJA
CAJA_ESTADO_ABIERTA = "abierta"
CAJA_ESTADO_CERRADA = "cerrada"

CAJA_MOVIMIENTO_INGRESO = "ingreso"
CAJA_MOVIMIENTO_EGRESO = "egreso"
CAJA_MOVIMIENTO_AJUSTE = "ajuste"

CAJA_ORIGEN_EGRESO_MANUAL = "egreso_manual"
CAJA_ORIGEN_AJUSTE_MANUAL = "ajuste_manual"
CAJA_ORIGEN_PAGO = "pago"

AUDITORIA_ENTIDAD_CREDITO = "credito"

AUDITORIA_ACCION_CREDITO_GENERADO = "credito_generado"
AUDITORIA_ACCION_CREDITO_APLICADO = "credito_aplicado"

DEUDA_ESTADO_ABIERTA = "abierta"
DEUDA_ESTADO_CERRADA = "cerrada"
DEUDA_ESTADO_ANULADA = "anulada"

DEUDA_MOVIMIENTO_CARGO = "cargo"
DEUDA_MOVIMIENTO_PAGO = "pago"
DEUDA_MOVIMIENTO_RECARGO = "recargo"
DEUDA_MOVIMIENTO_AJUSTE = "ajuste"
DEUDA_MOVIMIENTO_REVERSION = "reversion"

ORIGEN_DEUDA_CLIENTE = "deuda_cliente"

AUDITORIA_ENTIDAD_DEUDA = "deuda"
AUDITORIA_ACCION_DEUDA_GENERADA = "deuda_generada"
AUDITORIA_ACCION_DEUDA_PAGO_REGISTRADO = "deuda_pago_registrado"

# STOCK - MOVIMIENTOS
STOCK_MOVIMIENTO_INGRESO = "ingreso"
STOCK_MOVIMIENTO_VENTA = "venta"
STOCK_MOVIMIENTO_ENTREGA = "entrega"
STOCK_MOVIMIENTO_RESERVA = "reserva"
# IMPORTANTE:
# - devolucion_venta: solo para devoluciones de ventas entregadas
# - devolucion: uso interno (taller, ajustes, etc)
# NO USAR 'devolucion' para ventas
STOCK_MOVIMIENTO_DEVOLUCION = "devolucion"
STOCK_MOVIMIENTO_DEVOLUCION_VENTA = "devolucion_venta"
STOCK_MOVIMIENTO_AJUSTE_MANUAL = "ajuste_manual"

# STOCK - ORIGENES
ORIGEN_RESERVA = "reserva"
ORIGEN_ORDEN_TALLER = "orden_taller"
ORIGEN_AJUSTE_MANUAL = "ajuste_manual"

